Social Smell Documentation Updated
sailuh/kaiaulu pull request #157
Opened 2023-02-25 09:54 UTC by malialiu

Social_smell_showcase.md:
- Indicate recommended perceval version
- Example of getting necessary file path in different operating system
- Parse_gitlog function will contains path.expand (parser.R line 17)

- Some packages might not be downloadable by install.packages(“packages_name”), recommend possible solutions
Ex: devtools::install_github("matbmeijer/JirAgileR")

- On Ubuntu the libfontconfig1-dev package and libharfbuzz-dev package are required.
libfontconfig1-dev package: sudo apt -y install libfontconfig1-dev"
libharfbuzz-dev package: sudo apt-get install libharfbuzz-dev libfribidi-dev

2023-02-27 10:36 UTC, carlosparadis commented
Thank you Malia. I will get back to you on this.

2023-03-24 08:40 UTC, carlosparadis commented
Hi @malialiu. I think there is helpful information here, but it should be put on the wiki instead. Maybe create a new page on the Wiki called Troubleshooting and move the comments there.

2023-03-24 08:41 UTC, carlosparadis commented
I will leave the PR open as a reminder, but please move the info there first before closing it. Since everything is moving there, there is no need to merge this PR.

2023-03-24 08:42 UTC, carlosparadis requested changes
Please see notes in line.

2023-03-24 08:42 UTC, carlosparadis commented on vignettes/download_jira_data.Rmd
> +
This should be moved to the wiki, since it applies to other packages too

2023-03-24 08:42 UTC, carlosparadis commented on vignettes/download_jira_data.Rmd
> +conf <- yaml::read_yaml("../conf/thrift.yml")
This should not be modified

2023-03-24 08:42 UTC, carlosparadis commented on vignettes/social_smell_showcase.Rmd
> +libharfbuzz-dev package: sudo apt-get install libharfbuzz-dev libfribidi-dev
Please also move this to the wiki too

2023-03-24 08:42 UTC, carlosparadis commented on vignettes/social_smell_showcase.Rmd
> +libharfbuzz-dev package: sudo apt-get install libharfbuzz-dev libfribidi-dev
Can you also mention what they were required for? To run the notebook?

2023-03-24 08:42 UTC, carlosparadis commented on vignettes/social_smell_showcase.Rmd
> +conf_path <- "../conf/thrift.yml"
Should not be modified

2023-03-24 08:42 UTC, carlosparadis commented on vignettes/social_smell_showcase.Rmd
> +git_repo_path: C:/Users/myComputer/Documents/GitHub/thrift/.git
I am not sure we should include this either to the notebook, it seems function-specific instead.

2023-03-28 21:53 UTC, malialiu commented
Hi Carlos,

I have written some markdown for the wiki page, but I'm not sure how to add it without causing any issues. Can I share it here?

# 1. Installing R Packages

Sometimes, you may encounter difficulties when trying to install an R package using the standard `install.packages()` function, especially if the package is not available on the Comprehensive R Archive Network (CRAN). In such cases, you can try installing the package directly from GitHub using the `devtools` package.

To install a package from GitHub using devtools, you can use the `install_github()` function. For example, to install the `JirAgileR` package from GitHub, use the following command:

``` r
devtools::install_github("matbmeijer/JirAgileR")
```

This command will download and install the package from the GitHub repository.

On Ubuntu, you may encounter issues when trying to install `devtools` using the standard `install.packages()` function. This is often due to missing dependencies, such as the `systemfonts` package which requires `libfontconfig1-dev` and `libharfbuzz-dev`. Therefore, to resolve this issue, you can run the following command in the terminal:

    sudo apt-get install libharfbuzz-dev libfribidi-dev 

This command will help you install the missing dependencies for `systemfonts` and allow you to install packages using `devtools`.

2023-03-29 02:26 UTC, carlosparadis commented
Hi,

Please post to this wiki page I just made. You just need to click Edit and paste. Let me know if you are unable to see the edit button:

https://github.com/sailuh/kaiaulu/wiki/Troubleshooting

2023-03-29 03:09 UTC, malialiu commented
Hi Carlos,

I don't have an edit button on my side.

![image](https://user-images.githubusercontent.com/76604944/228416548-452ac614-d8d3-41c4-be97-3feb842e0e93.png)

2023-03-29 04:40 UTC, carlosparadis commented
Try now, I modified your permissions.

2023-03-29 06:11 UTC, malialiu commented
> Try now, I modified your permissions.

Thank you!

2023-03-29 06:34 UTC, carlosparadis commented
Looks good! Since the changes on the PR are all now on the wiki, I will close the PR. Let me know if I missed anything.

2023-03-29 06:34 UTC, closed without merging