Improving Kaiaulu documentation
sailuh/kaiaulu pull request #161
Opened 2023-02-28 09:27 UTC by nicoelee123

2023-02-28 09:27 UTC, nicoelee123 commented on README.md
> +    * Graph representation uses node + edge format, making it easier to extend analysis in popular graph tools such as Gephi and igraph library.
Makes it grammatically correct and easier to follow

2023-02-28 09:27 UTC, nicoelee123 commented on vignettes/blamed_line_types_showcase.Rmd
> +To identify line types, we must choose what types of lines are of our interest (e.g. functions, structs, etc). Kaiaulu chooses the line types from the project configuration file and uses [Universal C
Easier to follow

2023-02-28 09:28 UTC, nicoelee123 commented on vignettes/blamed_line_types_showcase.Rmd
> -[Kaiaulu's GitHub wiki page](https://github.com/sailuh/kaiaulu/wiki/Universal-Ctags) also provides more details on Universal Ctags various flags.
Grammatically correct

2023-02-28 09:28 UTC, nicoelee123 commented on vignettes/bug_count.Rmd
> +To establish bug count, we must map each file to its associated issue. In general (but not always), an open source project will adopt a commit message convention to label issue ids. For example, Kaia
Easier to understand

2023-02-28 09:28 UTC, nicoelee123 commented on vignettes/bug_count.Rmd
> +For each file, we now know the commits that were associated with fixing bugs. We then group the number of bug-related issues by file path. Our result should show the number of bugs per file path. The
Easier to understand

2023-02-28 09:28 UTC, nicoelee123 commented on vignettes/community_detection_showcase.Rmd
> +To facilitate the usage of the OSLOM algorithm, Kaiaulu currently provides two interface functions to its two binaries: `community_oslom` and `recolor_network_by_community`. The former requires the b
Misspelling

2023-03-16 04:32 UTC, carlosparadis requested changes
Hi,

These look fine. Could you git squash then into a single commit? 

Thanks!

2023-03-20 23:09 UTC, nicoelee123 commented
Hello,

I think I successfully combined the commits into a single commit. Please let me know if I didn't do it correctly. 

Thank you

2023-03-24 07:53 UTC, merged