Bugzilla crawler parser
sailuh/kaiaulu pull request #179
Opened 2023-04-08 10:45 UTC by malialiu

Here are the Bugzilla crawler parser functions. Let me know if I made any mistakes.
- parse_bugzilla_crawler_issue
- parse_bugzilla_crawler_comments

I didn't include 'issue_type' and 'issue_description' in the JSON file because I couldn't find them, and I also couldn't find 'comment_author_id.' But I did find the email of the comment author, which I extracted from the 'creator' field in the JSON file. I have put this email as the 'comment author_name' for now.

2023-04-11 03:54 UTC, carlosparadis requested changes
Very very minor request for changes here. Could you attach some example outputs? 

Also, now that Leilani has the code for her downloader, could you try using her code or request her files to ensure your functions are working correctly together? I think you should do that in an R Notebook, because this is what the Bugzilla Downloader Notebook should show (and so I can run it myself).

2023-04-11 03:54 UTC, carlosparadis commented on R/parser.R
> +#' Parse Bugzilla issues data obtained from json files from Bugzilla crawler
Use \code{\link{}} to explicitly refer to Leilani function and so when the user uses your function docs they can click and jump to it. 

In addition, use @seealso and include Leilani function there too. I have mentioned this in other revisions and I believe e-mails.

2023-04-11 03:54 UTC, carlosparadis commented on R/parser.R
> +#' Parse Bugzilla comments data obtained from json files from Bugzilla crawler
Same concern as the first comment on function cross-referencing.

2023-04-11 03:55 UTC, carlosparadis commented
> I didn't include 'issue_type' and 'issue_description' in the JSON file because I couldn't find them, and I also couldn't find 'comment_author_id.' But I did find the email of the comment author, which I extracted from the 'creator' field in the JSON file. I have put this email as the 'comment author_name' for now.

This is strange. @leilani-reich do you have any idea why these fields could not be found? The absence of type and description for issues are particularly worrisome, but we would like to have the comment author id too.

2023-04-22 05:17 UTC, malialiu commented
Hi Carlos,

I have just noticed that the first comment returned by "parse_bugzilla_crawler_comments" for each issue is actually the issue description. Should I make a column to put the issue description or leave it as a comment?

2023-04-22 05:50 UTC, carlosparadis commented
yes, I discussed this with @leilani-reich on our last call. But I no longer remember as to why. @leilani-reich do you remember?

2023-04-22 07:27 UTC, leilani-reich commented
@carlosparadis @malialiu For my perceval bugzilla parser functions, I made it so that the first comment, which was the issue description, would be excluded from the comment related fields in my table since it already appears in the issue related fields, like issue_description. And then I started counting comments as comments 2, 3, 4, +.

2023-04-22 07:34 UTC, carlosparadis commented
@leilani-reich Could you provide an example with an issue IRL, and maybe a screenshot like Malia did? I think what I want to be careful of here is if the actual issue description happens to appear as a first comment in the comments (meaning the API from Bugzilla is wrong, and you are correcting it on your code), or if we are making an assumption that the first comment is meant to be the issue description. An incorrect assumption here can compromise text mining analysis, so I want to make sure I understand.

2023-04-22 08:51 UTC, leilani-reich commented
For example, in this [issue](https://bugzilla.kernel.org/show_bug.cgi?id=217069), we see the image description and the first comment.
<img width="717" alt="Screenshot 2023-04-21 at 10 45 47 PM" src="https://user-images.githubusercontent.com/89750594/233773711-61af4429-92c2-4c14-bb16-c9e44dc37bdc.png">

The description will not appear as a comment in comment_body, it will only appear in the issue_description field, due to how I set my bugzilla downloader functions for perceval up.

Fields for the first row for the issue with id 217069:
<img width="765" alt="Screenshot 2023-04-21 at 10 48 36 PM" src="https://user-images.githubusercontent.com/89750594/233773966-d1bb0330-e45c-4c4c-b32d-4539c8d7cf13.png">
<img width="807" alt="Screenshot 2023-04-21 at 10 49 23 PM" src="https://user-images.githubusercontent.com/89750594/233773968-e01f01d0-7f13-4ac1-a9d0-376e44bdcdc5.png">

2023-04-22 09:03 UTC, malialiu commented
I modified my bugzilla crawler comment parser function, so it moved the first comment as issue description.

2023-04-23 06:16 UTC, leilani-reich commented
Hi Carlos, did you see my example here https://github.com/sailuh/kaiaulu/pull/179#issuecomment-1518567492 for the bugzilla issue? 

I know in https://github.com/sailuh/kaiaulu/pull/164#issuecomment-1518581298 you wanted to know whether the first comment being image description makes sense.

2023-04-23 07:19 UTC, carlosparadis commented
Reply to: https://github.com/sailuh/kaiaulu/pull/179#issuecomment-1518567492

No, sorry. It slip through. Thank you for the reminder. I still feel I am missing some information here, but the example is very helpful for me make an informed guess. You probably told me this already through other comments, but I need to see it all in one comment again so we can decide on this. Here's what I remember for the Crawler:

There is an issue endpoint, and a comment endpoint. You can download multiple issues per page per request (upper bounded by the limit imposed by the organization), but you can only download all comments per issue per request. 

1) Now, on the issue request, does the **API** provides you with a issue description? I think this is where I'm being forgetful. Did you tell me that in the issue request, the issue_description has the first comment of the issue? I am asking explicitly what the API gives you, not what you coded to be clear. 

2) Then the same question for the comment request: Does the **API** provides you with only comment body? Or does it provides you with both an issue description and a comment body?

I am trying to understand why you decided to make the comment_body API's first comment to populate the `issue_description`. Is it because that's what the issue API does? Or is there another reason? The **why** is what I am trying to understand so we can decide what makes the most sense.

2023-04-23 08:57 UTC, leilani-reich commented
Hi, I talk about your questions here https://github.com/sailuh/kaiaulu/pull/179#issuecomment-1518977862 for my Perceval bugzilla data specifically. I will double-check the bugzilla REST API data too.

2023-04-23 09:15 UTC, carlosparadis commented
Your comment above (https://github.com/sailuh/kaiaulu/pull/179#issuecomment-1519000527) redirects me to my own comment. I am a bit confused. Was it meant to the other comment I just replied with the screenshots of Perceval commands for Bugzilla?

2023-04-23 09:34 UTC, leilani-reich commented
Yes, I fixed the link. Thanks.

2023-04-24 12:42 UTC, carlosparadis commented
@malialiu Hi, yes this is OK! It should hopefully resolve once I accept the other PR in order, and you issue a merge commit here. Speaking of which, are we ready to start the PR accepts? If so, what order? did you finish the 3 asks on the notebook too? Just trying to remember where we at.

Thanks!

2023-04-29 11:19 UTC, carlosparadis commented
@malialiu Hi Malia,

The checks should now be working again (do a merge if not yet just in case too).

Please take a look on them to make sure they pass:

```
Warning: Missing link or links in documentation object 'parse_bugzilla_rest_comments.Rd':
  ‘download_bugzilla_rest_comments’
Missing link or links in documentation object 'parse_bugzilla_rest_issues.Rd':
  ‘download_bugzilla_rest_issues’
  ```
  
  Is the reason why the R-CMD-check is failing.

2023-04-29 11:36 UTC, malialiu commented
> Is the reason why the R-CMD-check is failing.
>
This seems like the reason it failed.
![image](https://user-images.githubusercontent.com/76604944/235300415-253b51d5-ee1b-42f7-8b8a-b3b5e4ecc5c7.png)

2023-04-29 11:52 UTC, carlosparadis commented
Try re-compiling the documentation so it generates the .Rd files and commit them alongside (the ones your function modified). If that doesn't fix the issue, there may be something needing to be fixed in the functions.

2023-04-29 12:43 UTC, malialiu commented
> Try re-compiling the documentation so it generates the .Rd files and commit them alongside (the ones your function modified). If that doesn't fix the issue, there may be something needing to be fixed in the functions.

It passes when I removed all the comments that link to the non-existent function.

2023-04-30 21:09 UTC, carlosparadis commented
@malialiu Hi Malia,

This merge conflict is more elaborated. Could you try to resolve the conflict just on this PR so I can try to accept it?

2023-04-30 23:59 UTC, malialiu commented
> @malialiu Hi Malia,
> 
> This merge conflict is more elaborated. Could you try to resolve the conflict just on this PR so I can try to accept it?

Yes! It should work right now.

2023-05-01 00:00 UTC, carlosparadis approved these changes
Looks good and passes the checks!

2023-05-01 00:15 UTC, merged