Create github.R
sailuh/kaiaulu pull request #301
Opened 2024-04-28 06:33 UTC by Ssunoo2

Script to call github refresh from the command line

2024-12-09 07:58 UTC, carlosparadis requested changes
pointing out here the get and other files ahead of time, same issue as @daomcgill

2024-12-09 07:58 UTC, carlosparadis commented on .github/workflows/R-CMD-check.yml
Make sure you revert this or sync to master

2024-12-09 07:58 UTC, carlosparadis commented on .github/workflows/test-coverage.yml
same on revert to master

2024-12-09 07:58 UTC, carlosparadis commented on exec/github.R
> +  repo <- conf[["issue_tracker"]][["github"]][["repo"]] # Has to match github repository (e.g. github.com/sailuh/perceive)
hardcoded get

2025-02-25 08:47 UTC, connorn-dev commented
@carlosparadis just added the code from Mbox. I kept github.R separate from my changes and added the vignette.

2025-02-25 08:56 UTC, carlosparadis commented
@connorn-dev sounds good i will go ahead and add a few quick notes as review to your code here

2025-02-25 09:02 UTC, carlosparadis requested changes
Here's some revision notes. Let me know if you have questions. I suggest you reply to the comment in question you want to iterate rather than an entirely separate comment so things are in context to the line of code.

2025-02-25 09:02 UTC, carlosparadis commented on exec/ghevents.R
> +  owner <- arguments[["<owner>"]]
Should use get() functions instead of direct access. See the cheat sheet associated to it for rationale on why.

2025-02-25 09:02 UTC, carlosparadis commented on vignettes/event_process_mining.Rmd
> +install.packages("reticulate")
You should not use reticulate. This is a strong dependency on Kaiaulu side. Rather, it is the Python script that should call this exec script.

2025-02-25 23:05 UTC, connorn-dev commented on exec/ghevents.R
> +  owner <- arguments[["<owner>"]]
So for example, to get the owner of the desired Github I should use "get_github_owner()" and rely on the configuration file for the users input?

2025-02-25 23:21 UTC, carlosparadis commented on exec/ghevents.R
> +  owner <- arguments[["<owner>"]]
The path to the configuration file should be passed to your /exec. However, to load the config from the path, and the subsequent accesses to get field information should use get() functions. The functions exist on R/config.R. if it doesn't exist, you should define new ones. See "accessing configs from Notebooks". That also applies to configs: https://github.com/sailuh/kaiaulu_cheatsheet/blob/main/cheatsheets/project-analysis-cheatsheet.pdf 

https://github.com/sailuh/kaiaulu/blob/c5922608d8a88287767a523bc9194ee9ae032b0b/exec/mailinglist.R#L89-L90

Not all the code on PR is fully reviewed (I see Dao missed the config get to load the file), but it exists: 

https://github.com/sailuh/kaiaulu/blob/ac522b6fd675230da905c0b54b241904e6c76705/R/config.R#L21-L30

See the cheatsheet linked above why we enforce the get() this was a major milestone for the Fall'24 group : )

2025-05-06 12:21 UTC, carlosparadis requested changes
Looks fine on this side. Commits are blended to older PR so I can only do a cursory overview. Please disregard the request change, this is a note to self when I work on the merge over the Summer.

2025-05-06 12:21 UTC, carlosparadis commented on vignettes/event_process_mining.Rmd
Hmm. Up to this point notebooks document the API, not the execs. I will need to give more thought on this in the future.

2025-09-25 00:41 UTC, geraldmjhuff commented on exec/ghevents.R
> +  all_issue_event <- lapply(all_issue_event, github_parse_project_issue_events)
@carlosparadis The function github_parse_project_issue_events is a R/github.R function but R/github.R is not sourced at the top

2025-09-25 00:41 UTC, geraldmjhuff commented on exec/ghevents.R
> +  github_events.R --version
CLI docs still refer to github_events.R. To stay consistent with the actual script name, this should be updated to ghevents.R

2025-09-25 00:41 UTC, geraldmjhuff commented on exec/github.R
> +
source("R/config.R")
source("R/github.R")
should be added here since functions are called from those files.

2025-09-25 00:41 UTC, geraldmjhuff commented on exec/github.R
> +                             verbose = TRUE)
The call to github_api_iterate_pages() includes verbose = TRUE, but the function doesn’t accept a verbose argument. Consider removing verbose = TRUE here to fix the error. This also occurs in lines 80 and 90.

2025-09-25 00:41 UTC, geraldmjhuff commented on exec/github.R
> +    github_api_iterate_pages(token,gh_response,
gh_response is used here but it isn't defined. Adding gh_response <- github_api_project_issue_or_pr_comments(owner, repo, token) before it is used within this else if block fixes it.

2025-09-25 00:56 UTC, carlosparadis commented on exec/ghevents.R
> +  all_issue_event <- lapply(all_issue_event, github_parse_project_issue_events)
Nice catch! Could you check if source is required for /exec to work? For R/ functions within an R package we do not need to use source, so it would be nice to check we are using the appropriate method for R packages specifically.

2025-09-25 00:57 UTC, carlosparadis commented on exec/ghevents.R
> +  github_events.R --version
Could you check the other exec to see which should we stick with for consistency? E.g. if the others are all github_* then it may be best we move ghevents to github_events.R throughout the code.

2025-09-25 00:59 UTC, carlosparadis commented on exec/github.R
> +
I see require above as opposed to source, is there a reason you are suggesting source instead of require? In Noteboks we also use require. I suspect this PR predates when we created the config module. It may be a good idea for you to also see the cheat sheet about configs as you will be relying n it when coding on the /exec folder. I.e. the cheat sheet should explain you why we decided to create a bunch of get_ functions to read the config instead of just parsing directly!

2025-09-25 01:02 UTC, carlosparadis commented on exec/github.R
> +                             verbose = TRUE)
What about https://github.com/sailuh/kaiaulu/blob/ac522b6fd675230da905c0b54b241904e6c76705/R/github.R#L580 ?

2025-09-25 01:04 UTC, carlosparadis commented on exec/github.R
> +    github_api_iterate_pages(token,gh_response,
Isn't it defined on line 64? This is the entirety of the code block after it is defined:

https://github.com/sailuh/kaiaulu/blob/8b0582539bbb18b8d4d2f2e410abe554b4c5acba/exec/github.R#L64-L90

2025-09-25 01:06 UTC, carlosparadis commented on exec/ghevents.R
> +  all_issue_event <- lapply(all_issue_event, github_parse_project_issue_events)
Looking at the requirement list, I see: 

https://github.com/sailuh/kaiaulu/blob/8b0582539bbb18b8d4d2f2e410abe554b4c5acba/exec/github.R#L12C17-L12C24 

As Kaiaulu is an R package, all files in Kaiaulu and its API should be loaded using this command. Did the code not rn for you?

2025-09-25 01:06 UTC, carlosparadis commented on exec/github.R
> +
Looking at the requirement list, I see: 

https://github.com/sailuh/kaiaulu/blob/8b0582539bbb18b8d4d2f2e410abe554b4c5acba/exec/github.R#L12C17-L12C24 

As Kaiaulu is an R package, all files in Kaiaulu and its API should be loaded using this command. Did the code not rn for you?

2025-09-25 01:07 UTC, carlosparadis commented
This is good progress, thank you for doing the code review. Have you downloaded this branch, and tried to run this exec yet?

2025-09-25 01:40 UTC, geraldmjhuff commented on exec/github.R
> +    github_api_iterate_pages(token,gh_response,
gh_response in line 64 was defined within the scope of the 1st if block. Since gh_response was called in line 87 in the 3rd if block, it doesn't see gh_response. 

I tested both scenarios where I'd add gh_response <- github_api_project_issue_or_pr_comments(owner, repo, token) in line 85 and one without it. The one without it gave me this error: Error: object 'gh_response' not found
Execution halted

2025-09-30 02:29 UTC, geraldmjhuff reviewed
@carlosparadis Made comments on the event_process_mining.Rmd and github_api_showcase.Rmd notebooks

2025-09-30 02:29 UTC, geraldmjhuff commented on vignettes/event_process_mining.Rmd
> +command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
Assuming this notebook runs in the vignettes directory, lines 50 and 53 contains exec/ghevents.R which should be changed to ../exec/ghevents.R since to run that the ghevents.R script it has to move one directory up before it can access exec/ghevents.R. If these commands are supposed to be ran in the root directory, this can be ignored.

Same should be applied to conf/process_mining.yml, instead it should be ../conf/process_mining.yml to access the conf folder if this notebook were to be ran in vignettes directory.

Note: process_mining.yml does not currently exist within this branch nor the master branch. I had to temporarily change process_mining.yml to kaiaulu.yml to test this notebook. Pushing this PR to master branch when process_mining.yml does not exist on either branch could be misleading.

2025-09-30 02:29 UTC, geraldmjhuff commented on vignettes/github_api_showcase.Rmd
In save_path <- path.expand(conf[["issue_tracker"]][["github"]][["replies"]]) , tries to access "replies" in kaiaulu.yml but that key does not exist.

2025-09-30 02:31 UTC, geraldmjhuff commented on exec/ghevents.R
> +  all_issue_event <- lapply(all_issue_event, github_parse_project_issue_events)
I see my mistake; I haven't properly installed the packages and therefore I had to source both scripts. After installing the packages, it works as intended and sourcing those two scripts are no longer necessary.

2025-09-30 02:46 UTC, geraldmjhuff commented on exec/github.R
> +  github refresh <project_conf.yml> <project_key> [--issues | --comments | --pr]
Parse commands require running refresh first to download the GitHub JSON files; otherwise, CSV outputs will be empty. For documentation purposes, it would be better if the refresh commands are above the parse commands in this documentation in the case that the user wants to run these in a linear order.

2025-09-30 02:47 UTC, geraldmjhuff commented on exec/github.R
> +
I see my mistake; I haven't properly installed the packages and therefore I had to source both scripts. After installing the packages, it works as intended and sourcing those two scripts are no longer necessary.

2025-09-30 02:52 UTC, carlosparadis commented on exec/github.R
> +
No worries, it is a common mistake!

2025-09-30 04:22 UTC, carlosparadis commented on vignettes/event_process_mining.Rmd
> +command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
Thank you for catching this. Unfortunately, this notebook implementation is incorrect. So I am glad you found it and asked me about it to avoid also doing the same. You see, the R notebook in Kaiaulu purpose is to explain to the user how to use Kaiaulu API (functions in R/) to write their own analysis. So, although the code here is functional, it is not complying to Kaiaulu architecture. There is also no reason to use the script when the user can just use the R function, it is an R notebook afterall.

The place which the exec should be used is *outside* Kaiaulu. This generally makes more sense if you are using another language, in which case you will not have the ability to call an R function directly or it is less desirable. For example, @austindang67 would want to issue a command line call to Kaiaulu to get the data he needs. This also keeps his side of the code clean on the frontend (the only responsability of the frontend is to request data from Kaiaulu, not preprocess it, etc). 

Does that make sense? So the fix here would be to go to the script exec/ghevents.R and bring in the code block that is calling functions there into the notebook. In the notebook you may have a few code blocks and english around the code blocks explaining it. 

Or is this code just cited here to acknowledge it exists and the rest of the notebook goes API function-wise?

2025-09-30 04:28 UTC, carlosparadis commented on vignettes/github_api_showcase.Rmd
This is also outdated code, so thank you for catching this. The notebook should not be accessing directly the attributes of the conf folder. Rather, it should be using the get() functions defined in R/conf.R. The reason for that is simple: The conf architecture (the layout of how information is formatted) changes from time to time. You can imagine that every time that file changes, well, everything on Kaiaulu has to change which is a massive undertake. 

A few sessions back, one group worked on an interface to access the fields using get() functions. Please have a look on this cheatsheet: https://github.com/sailuh/kaiaulu_cheatsheet/blob/main/cheatsheets/project-analysis-cheatsheet.pdf on the middle top, "Accessing Configs from Notebooks". It goes over that.

So the fix here is to replace the functions with get() from R/config.R. 

I also hope you see here why the data cheatsheets exist for when you get around working on yours: They simplify conceptual design decisions we made in Kaiaulu that prevent the code to devolve into chaos. Once you understand the underlying idea there, you can apply the principle when writing your own code. 

Good work on finding these issues!

2025-09-30 04:31 UTC, carlosparadis commented on exec/github.R
> +  github refresh <project_conf.yml> <project_key> [--issues | --comments | --pr]
This makes a lot of sense, please implement this change. I am also glad you encountered the refresh feature here. This also has a cheatsheet: https://github.com/sailuh/kaiaulu_cheatsheet/blob/main/cheatsheets/refresher-cheatsheet.pdf 

Please take a look so you understand the core idea of why we named it "refresh". It is just an idea to simplify how users can get data without having to re-download everything and keeping on .csv files rather than add a whole database requirement to setup Kaiaulu. This was also a prior student group contribution!

Nice catch!

2025-09-30 04:40 UTC, carlosparadis commented on exec/github.R
> +    github_api_iterate_pages(token,gh_response,
Sorry, I replied without looking at the notebook. You are correct, this was likely an oversight: Every IF code block has more or less the same look and feel:

https://github.com/sailuh/kaiaulu/blob/8b0582539bbb18b8d4d2f2e410abe554b4c5acba/exec/github.R#L61-L71

and

https://github.com/sailuh/kaiaulu/blob/8b0582539bbb18b8d4d2f2e410abe554b4c5acba/exec/github.R#L72-L82

both have ghresponse.

However the one you pointed out is missing:

https://github.com/sailuh/kaiaulu/blob/8b0582539bbb18b8d4d2f2e410abe554b4c5acba/exec/github.R#L83-L92

Meaning no data is being downloaded here. So this is a mistake. Please add the line here. Also thank you for trying to run the code while reviewing it (sometimes people don't! )

I also recommend you give some thought about all these GitHub endpoints we use:

We have a few for issues and a few for PR. The issue endpoints are for issue body and issue comment. However, the PR is far more complicated than what appears on the surface. We spent a lot of time making a cheatsheet about it. I encourage you take a look: https://github.com/sailuh/kaiaulu_cheatsheet/blob/eda5e0017419a2746fe823156c19798ae862fe76/cheatsheets/github-comments-cheatsheet.pdf 

As you can see, there is a fair amount of cheatsheets around Kaiaulu. As you learn from them, use it as an exercise to consider what is the best visual representation to convey an idea without using too many words. Just imagine how many meetings we would need or walls of text absent all the cheatsheets I shared over the past 10 minutes across the comments!

2025-10-02 11:08 UTC, geraldmjhuff commented on vignettes/event_process_mining.Rmd
> +command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
In that case, we can leave the ghevents.R CLI commands as it is so people can see how to run the steps outside of R but exclude those commands from being ran in a code chunk since we do not want it to run in the notebook. Right after, we show the same steps using R functions that is implemented in a runnable code chunk. This way, people can learn both how the CLI works and how to do it in R. 

Directly under the CLI commands, we can implement the R API functions equivalent of the CLI commands with the proper text:

In this notebook, the following code chunk shows the equivalent workflow using Kaiaulu R API functions, which can be run interactively and reproduces the same results as the CLI commands.
```
# Equivalent workflow using Kaiaulu R API functions.
# This can be run interactively and reproduces the same results as the CLI commands.
library(kaiaulu)
library(data.table)
library(jsonlite)

conf <- parse_config("../conf/process_mining.yml")
owner <- get_github_owner(conf, "project_key_1")
repo <- get_github_repo(conf, "project_key_1")
save_path <- get_github_issue_event_path(conf, "project_key_1")
token_path <- "~/.ssh/github_token"
output_file <- "../output.csv"

token <- scan(token_path, what="character", quiet=TRUE)
if(!dir.exists(save_path)) dir.create(save_path, recursive=TRUE)

# Download GitHub issue events 
gh_response <- github_api_project_issue_events(owner, repo, token)
github_api_iterate_pages(token, gh_response, save_path, prefix="issue_event")

#  Parse downloaded JSON files 
json_files <- list.files(save_path, full.names=TRUE)
all_issue_event <- lapply(json_files, read_json)
all_issue_event <- lapply(all_issue_event, github_parse_project_issue_events)
all_issue_event <- rbindlist(all_issue_event, fill=TRUE)
all_issue_event[, issue_body := NULL]

write.csv(all_issue_event, output_file, row.names=FALSE)
```

I've tested this implementation (with ../conf/kaiaulu.yml since process_mining.yml does not exist) in my code space in place of the two commands and it yielded the same results. I've also included comments to show what parts of the code downloads and parses. Also the config process_mining.yml is being parsed here, considering that .yml currently does not exist in this branch, should it be changed to kaiaulu.yml?

2025-10-02 11:08 UTC, geraldmjhuff commented on vignettes/github_api_showcase.Rmd
The lines 47 to 49 can be replaced with:

```
owner <- get_github_owner(conf, "project_key_1") # Has to match github organization (e.g. github.com/sailuh)
repo <- get_github_repo(conf,"project_key_1") # Has to match github repository (e.g. github.com/sailuh/perceive)
save_path <- path.expand(get_github_issue_or_pr_comment_path(conf, "project_key_1")) # Path you wish to save all raw data. A folder with the repo name and sub-folders will be created. 
```

This uses the get() functions from R/config.R which is functionally equivalent.

2025-10-03 12:49 UTC, geraldmjhuff commented on vignettes/event_process_mining.Rmd
> +command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
@carlosparadis I'm pinging now in the case you were not notified of my above comment ^

2025-10-03 12:49 UTC, geraldmjhuff commented on vignettes/github_api_showcase.Rmd
@carlosparadis I'm pinging now in the case you were not notified of my above comment ^

2025-10-03 13:33 UTC, carlosparadis commented on vignettes/event_process_mining.Rmd
> +command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
I missed this. 

I suggest you still remove the CLI mention altogether. The main concern here is that, should the CLI be changed in the future (as you are doing now), we will need to keep tabs on which Notebook may be trying to explain it. If we forget it, then it becomes outdated. This type of implicit dependency is hard to manage, hence the requirement to keep the Notebooks as API only.

The project configuration file, however, I do feel we should explain at the start, as it clarifies what information is needed to run the notebook and the API specifically. 

> Also the config process_mining.yml is being parsed here, considering that .yml currently does not exist in this branch, should it be changed to kaiaulu.yml? 

Presuming you will need to merge master into this branch (note who is being merged to who) in order to eventually merge this PR to master, wouldn't kaiaulu.yml be added here at that point?

2025-10-03 13:33 UTC, carlosparadis commented on vignettes/github_api_showcase.Rmd
If the get() functions already exist, I agree you can proceed with this!

2025-10-07 07:32 UTC, geraldmjhuff commented on vignettes/event_process_mining.Rmd
> +command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
@carlosparadis I've rewritten the notebook to no longer mention any CLI, explained the use case of the project config file and why it's necessary, and shifted to an API-only related text notebook that explains how to download and parse repo's using functions from ghevents.R. Process_mining is mentioned to let the user know a use case for the parsed saved data.

This is the current code that is working as intended in my codespace: 

---
title: "Event Process Mining"
output: 
  html_document:
    toc: true
    number_sections: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Event Process Mining}
  %\VignetteEncoding{UTF-8}
---

# Introduction

This notebook demonstrates how to use the **Kaiaulu R API** functions defined in `ghevents.R`  
to download and parse GitHub issue event data using the GitHub API.  
This data can be used for various analysis and use cases. A possible use case is process mining analysis, to see an example for process mining refer to this [repo](https://github.com/sailuh/process_mining).

## Requirements

- **GitHub Access Token**  
  Used for authentication when accessing the GitHub REST API.

- **Kaiaulu**  
  Provides the API functions implemented in `ghevents.R` for retrieving and parsing GitHub event data.

## Project Configuration File

To simplify setup and ensure consistency, Kaiaulu uses a configuration file (e.g., `kaiaulu.yml`)  
that defines project-specific parameters such as the GitHub owner, repository name, and data storage paths.  

This configuration file enables the API functions to locate repositories and determine where to store downloaded and parsed data.  
The content that interests us for this notebook is primarily the `issue_event` download path.  

By parsing this configuration file at the start, the notebook clearly communicates **all information needed to run the API functions**:  

- Which GitHub organization (`owner`) and repository (`repo`) to query  
- Where to save raw JSON issue event data (`issue_event`)  
- Which token to use for authentication (`token_path`)  
- Where to export the processed CSV (`output_file`)  

This ensures that the notebook workflow is fully reproducible and that users do not need to manually supply repository details or paths.

An example configuration snippet from `kaiaulu.yml`:

    ```        
    github:
        project_key_1:
          # Obtained from the project's GitHub URL
          owner: sailuh
          repo: kaiaulu
          # Download using `download_github_comments.Rmd`
          issue_or_pr_comment: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue_or_pr_comment/
          issue: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue/
          issue_search: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue_search/
          issue_event: ../rawdata/kaiaulu/github/sailuh_kaiaulu/issue_event/
          pull_request: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/pull_request/
          commit: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/commit/

    ```
## Download and Parse GitHub Issue Event Data

The following code demonstrates the full workflow of the Kaiaulu R API to:

1. Load the project configuration file to obtain necessary parameters (owner, repo, paths, and token).  
2. Download all GitHub issue event data for the specified repository.  
3. Parse the raw JSON files into a clean tabular format.  
4. Export the processed data to a CSV file for downstream analysis, such as process mining.

```{r}
library(kaiaulu)
library(data.table)
library(jsonlite)

conf <- parse_config("conf/kaiaulu.yml")
owner <- get_github_owner(conf, "project_key_1")
repo <- get_github_repo(conf, "project_key_1")
save_path <- get_github_issue_event_path(conf, "project_key_1")
token_path <- "~/.ssh/github_token"
output_file <- "../output.csv"

token <- scan(token_path, what="character", quiet=TRUE)
if(!dir.exists(save_path)) dir.create(save_path, recursive=TRUE)

# Download GitHub issue events 
gh_response <- github_api_project_issue_events(owner, repo, token)
github_api_iterate_pages(token, gh_response, save_path, prefix="issue_event")

#  Parse downloaded JSON files 
json_files <- list.files(save_path, full.names=TRUE)
all_issue_event <- lapply(json_files, read_json)
all_issue_event <- lapply(all_issue_event, github_parse_project_issue_events)
all_issue_event <- rbindlist(all_issue_event, fill=TRUE)
all_issue_event[, issue_body := NULL]

write.csv(all_issue_event, output_file, row.names=FALSE)
```

### Next Steps: Process Mining Analysis

The processed GitHub issue event data is now saved in `output.csv`.  
If you want to perform process mining analysis, you can use the [Process Mining Notebook](https://github.com/sailuh/process_mining),  
which relies on Python and the `pm4py` package to analyze issue event data.

2025-10-07 09:03 UTC, carlosparadis commented on vignettes/event_process_mining.Rmd
> +command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
It is not viable for me to comment on such a large piece of text without inline code review. Can you push the commit with the new version and issue a code review request for me?

2025-10-07 10:42 UTC, geraldmjhuff commented on vignettes/event_process_mining.Rmd
> +command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
@carlosparadis To clarify, did you want me to choose the option "Create a new branch and then start a pull request" when within the "Commit changes" pop up window?

2025-10-07 11:13 UTC, carlosparadis commented on vignettes/event_process_mining.Rmd
> +command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
@geraldmjhuff, I am actually now confused about what is going on here. Can you do this for me: Ping me on the issue associated to this task (so I can get context about it), and then paste this comment (https://github.com/sailuh/kaiaulu/pull/301#discussion_r2409672770) so  I can follow-up. With that said, I did not intend to suggest a new issue or PR. I assumed whatever notebook you posted here was already part of this PR/branch and you pasted it on a comment on the PR instead of just making a commit changing it. Regardless, please post on the issue this comment for us to iterate there since this is relevant for memory keeping.

For future reference: Discussion on PR will rarely be seen again (since it is a very specific need to go back to a code review via git blame), but the issues will be important in the future.

Thanks!

2025-11-10 10:13 UTC, geraldmjhuff commented
@carlosparadis When using this command for exec/github.R, I was prompted:
```
@geraldmjhuff ➜ /workspaces/kaiaulu (298-github-refresh-script) $ Rscript exec/github.R parse conf/kaiaulu.yml output.csv project_key_1 --issues
Error in data.table::fwrite(all_issue, save_path) : 
  Row 144 of list column is type 'NULL' - not yet implemented. fwrite() can write list columns containing items which are atomic vectors of type logical, integer, integer64, double, complex and character.
Execution halted
```
Which infers that there exists at least one NULL value within a column in one of the tables rows. This problem occurs in two code blocks: 
```
if (arguments[["--issues"]]) {
    save_path_issue <- get_github_issue_path(conf, project_key)

    all_issue <- lapply(list.files(save_path_issue,
                                   full.names = TRUE),read_json)
    all_issue <- lapply(all_issue,
                        github_parse_project_issue)
    all_issue <- rbindlist(all_issue,fill=TRUE)

    data.table::fwrite(all_issue, save_path)
    cli::cli_alert_success(paste0("Dependencies table was saved at: ", save_path))
  }
```
and 
```
else if(arguments [["--pr"]]){
    save_path_pull_request <- get_github_pull_request_path(conf, project_key)

    all_pr <- lapply(list.files(save_path_pull_request,
                                full.names = TRUE),read_json)
    all_pr <- lapply(all_pr,
                     github_parse_project_pull_request)
    all_pr <- rbindlist(all_pr,fill=TRUE)

    data.table::fwrite(all_pr, save_path)
    cli::cli_alert_success(paste0("Dependencies table was saved at: ", save_path))
  }
```
The fix would be to change any NULL values in any row/column of the table to NA right before data.table::fwrite(all_pr, save_path). I've implemented the fix in my environment and both code blocks were able to execute without this error. Would it be permissible to have NA values replace the NULL values to get the code to run? I believe this is the last change before this PR is ready to be reviewed.

2025-11-10 11:57 UTC, carlosparadis commented
@geraldmjhuff forcing a NULL to become NA without knowing why is a recipe for disaster down the road. NAs carry the meaning of "missing data". But we don't know why the NULL occurs, do we? Not sure if I missed something in the chain of comments. If we assign it to NA we are **assuming** it is missing data. But we don't know if it is code logic. 

What I recommend you do is to run the same code on the Notebook side or just make a quick Notebook and run so you can inspect the data. I.e. which issue or comment or PR causes that? What is so special about it to trigger a problem? I presume the raw data is not the issue, so the error likely occurs in the parser. Try to pinpoint the row and see what in the JSON is causing the NULL in the first place. 

Does that make sense? 

The ideal solution is to identify the source of the NULL, confirm we are on the same page, and add an if statement that accounts for the specific case and explain it with a comment, likely within the parser function, presuming that's where the problem is happening. 

There is actually a module within Kaiaulu that goes by "fake data generator". Using the example in the data, I can use the function there to generate an artificial data sample on the fly and tie a unit test to it. Hence, preventing this from ever happening again (since the CI/CD on GitHub Actions will run to check for it every time). 

If you did an "All NULL - NA" anywhere else please reverse and use this approach.

2025-11-10 12:08 UTC, geraldmjhuff commented
@carlosparadis Wary of the concerns of this implementation, I have not pushed anything regarding changing NULL to NA on the tables, but that implementation is currently in my environment just to get the code block to execute. Ill revert this implementation on my environment and pinpoint the source and propose a solution before making the change.

2025-11-10 13:11 UTC, carlosparadis commented
Sounds like a plan! Since I expect you will run into this issue on the notebook end as well, I believe it is worth the investigation (and this is a contribution nonetheless to a dataset many people use).

Do remember, however, that based on what we last spoke about, you will no longer be using the /exec on the final version of the deliverable, but rather a notebook (architecture 3). In it, it is the Python script that is called in the notebook via an R function, as we do with parse_gitlog, asking for Perceval binary path from tools.yml. 

I did ask you to consider the pros/cons of the architectures, but unless something comes to mind I am presuming we are following that path.

2025-11-10 13:55 UTC, geraldmjhuff commented
@carlosparadis I've pinpointed the source. In my environment, I've created a loop that shows me any rows that contain a NULL value in any column of the table. Out of all listed columns, only the "body" column contains NULL values. Here's is a snippet of the results of that loop being executed:
```
Column 'body' has NULLs in rows: 144, 145, 182, 188, 189, 227, 233, 234, 238, 266, 270
 1:             Adding bugzilla wrapper functions unit tests [NULL]
 2:             Adding bugzilla wrapper functions unit tests [NULL]
 3:                     Adding unit tests to interval module [NULL]
 4:                          Improving Kaiaulu documentation [NULL]
 5:                 Fixing documentation grammar and wording [NULL]
 6:            Add sentiment comment exporter for issue #346 [NULL]
 7: 321 creating a file directory with functions in config.R [NULL]
 8:                 324 GitHub discussions with graph ql api [NULL]
 9:                         310 Parallelize Refresh Pipeline [NULL]
10:                  i #296 Jira exec works from commandline [NULL]
11:                        285 Bugzilla Downloader Refresher [NULL]
```
These are the associated issues:
```
1: https://api.github.com/repos/sailuh/kaiaulu/issues/205 2023-05-03T12:45:55Z
 2: https://api.github.com/repos/sailuh/kaiaulu/issues/204 2023-05-03T12:27:44Z
 3: https://api.github.com/repos/sailuh/kaiaulu/issues/167 2023-03-18T20:30:52Z
 4: https://api.github.com/repos/sailuh/kaiaulu/issues/161 2023-02-28T09:27:08Z
 5: https://api.github.com/repos/sailuh/kaiaulu/issues/160 2023-02-28T07:58:35Z
 6: https://api.github.com/repos/sailuh/kaiaulu/issues/347 2025-03-27T12:37:46Z
 7: https://api.github.com/repos/sailuh/kaiaulu/issues/333 2024-12-09T00:01:19Z
 8: https://api.github.com/repos/sailuh/kaiaulu/issues/332 2024-12-08T22:23:28Z
 9: https://api.github.com/repos/sailuh/kaiaulu/issues/328 2024-11-12T22:17:31Z
10: https://api.github.com/repos/sailuh/kaiaulu/issues/297 2024-04-23T23:58:12Z
11: https://api.github.com/repos/sailuh/kaiaulu/issues/293 2024-04-06T00:29:51Z
```
For each of these issues JSON, they all have "body":null
The first row (Row 144) is exactly why this error came up in my earlier comment: 
```
@geraldmjhuff ➜ /workspaces/kaiaulu (298-github-refresh-script) $ Rscript exec/github.R parse conf/kaiaulu.yml output.csv project_key_1 --issues
Error in data.table::fwrite(all_issue, save_path) : 
  Row 144 of list column is type 'NULL' - not yet implemented. fwrite() can write list columns containing items which are atomic vectors of type logical, integer, integer64, double, complex and character.
Execution halted
```
Therefore, it is inferred the other mentioned rows (145, 182, 188, 189, 227, 233, 234, 238, 266, 270) have the same problem. Due to this, it is a parser problem, specifically github_parse_project_issue() in R/github.R:
```
github_parse_project_issue <- function(api_responses){
  parse_response <- function(api_response){
    parsed_response <- list()
    parsed_response[["issue_id"]] <- api_response[["id"]]
    parsed_response[["issue_number"]] <- api_response[["number"]]
    parsed_response[["html_url"]] <- api_response[["html_url"]]
    parsed_response[["url"]] <- api_response[["url"]]
    parsed_response[["created_at"]] <- api_response[["created_at"]]
    parsed_response[["updated_at"]] <- api_response[["updated_at"]]
    parsed_response[["state"]] <- api_response[["state"]]
    parsed_response[["issue_user_login"]] <- api_response[["user"]][["login"]]
    parsed_response[["author_association"]] <- api_response[["author_association"]]
    parsed_response[["title"]] <- api_response[["title"]]
    parsed_response[["body"]] <- api_response[["body"]]

    parsed_response[["labels"]] <- api_response[["labels"]]
    if(length(parsed_response[["labels"]]) > 0){
      parsed_response[["labels"]] <- stringi::stri_c(sapply(parsed_response[["labels"]],"[[","name"),collapse = ",")
    }else{
      parsed_response[["labels"]] <- NA_character_
    }

    parsed_response <- as.data.table(parsed_response)

    return(parsed_response)
  }
  rbindlist(lapply(api_responses,parse_response),fill=TRUE)
}
```
On further inspection, we can see that the only multi-line parser is parsed_response[["labels"]], and it has an else block that fills in the labels with NA if it returns an empty list. Im assuming because they all share the same JSON problem of having "body":null, would the fix be to change null to NA for parsed_response[["body"]], similar to how parsed_response[["labels"]] changes a label value to NA if no labels exist?

2025-11-10 16:25 UTC, carlosparadis commented
I think you are still thinking this too much from a code perspective. Did you try looking at the original issue via browser to understand what is causing the NULL? I took a quick look and it seems to be cases where the issue has `No description provided` stated on it. Is that the case?

What I am finding a bit strange is that I can run the notebook just fine on my end to compile the docs. Could you check the associated notebook also run in the same issue?

Presuming what I am saying above is correct in regards to the no description, then add a if() not null and add a comment above saying "for cases where no description provided on the issue/PR is displayed". The key thing here is that the condition now has clear rationale for existing. 

Please do check on the browser the offending issues assert the assumption above and the situation with the notebook.

Also could you post a sample of one of these issues JSON here that has no description, and one that does for reference? use the 3 ticks with the word json in front of it.

2025-11-11 03:36 UTC, geraldmjhuff commented
I've looked into all mentioned issues on the browser and for each, they all have `No description provided`. For each of the issues (205, 204, 167, 161, 160, 347, 333, 332, 328, 297, 293) JSON, they share the same body value.

Here is the body key for the JSON for all issues:
```json
"body": null
```
Here is a different issues body other than the ones listed:
```json
"body": "Some .git repos contain over 1GB of data. overall, parsed objects should just be serialized as .rds to speed up further exploratory analysis."
```

2025-11-11 04:07 UTC, carlosparadis commented
Thank you for conducting the investigation! If this is the case then, are we in agreement that:

```r
parsed_response[["body"]] <- api_response[["body"]]
```

will be wrapped in an if(!is.null) statement, with a comment above it stating this controls for the `No description provided` cases? I would not add the if to the rest, as we would rather diagnose at the time the cause of the issue (especially since you can't post a comment without any description, as you can with an issue).  


```r
github_parse_project_issue <- function(api_responses){
  parse_response <- function(api_response){
    parsed_response <- list()
    parsed_response[["issue_id"]] <- api_response[["id"]]
    parsed_response[["issue_number"]] <- api_response[["number"]]
    parsed_response[["html_url"]] <- api_response[["html_url"]]
    parsed_response[["url"]] <- api_response[["url"]]
    parsed_response[["created_at"]] <- api_response[["created_at"]]
    parsed_response[["updated_at"]] <- api_response[["updated_at"]]
    parsed_response[["state"]] <- api_response[["state"]]
    parsed_response[["issue_user_login"]] <- api_response[["user"]][["login"]]
    parsed_response[["author_association"]] <- api_response[["author_association"]]
    parsed_response[["title"]] <- api_response[["title"]]
    parsed_response[["body"]] <- api_response[["body"]]

    parsed_response[["labels"]] <- api_response[["labels"]]
    if(length(parsed_response[["labels"]]) > 0){
      parsed_response[["labels"]] <- stringi::stri_c(sapply(parsed_response[["labels"]],"[[","name"),collapse = ",")
    }else{
      parsed_response[["labels"]] <- NA_character_
    }

    parsed_response <- as.data.table(parsed_response)

    return(parsed_response)
  }
  rbindlist(lapply(api_responses,parse_response),fill=TRUE)
}
```

2025-11-11 04:26 UTC, geraldmjhuff commented
@carlosparadis Additionally to clarify why the notebook may be working, it may be because the error occurs in github_parse_project_issue() calls, but the notebook doesn't call this function. 

I've also didnt mention but also decided to inspect another function with a similar problem and found out that github_parse_project_pull_request() shares the exact same problem. This is the call using --pr instead:
```
@geraldmjhuff ➜ /workspaces/kaiaulu (298-github-refresh-script) $ Rscript exec/github.R parse conf/kaiaulu.yml output.csv project_key_1 --pr
Error in data.table::fwrite(all_pr, save_path) : 
  Row 2 of list column is type 'NULL' - not yet implemented. fwrite() can write list columns containing items which are atomic vectors of type logical, integer, integer64, double, complex and character.
Execution halted
@geraldmjhuff ➜ /workspaces/kaiaulu (298-github-refresh-script) $ 
```
Again, I've created a loop that shows where NULL occurs, similar to the other function, all issues here as well have the exact same problem of having `No description provided` and that each have a body value of NULL. This function as well was not used in the github_api_showcase.Rmd notebook which may be why the notebook was able to run. Should I apply the same solution to this function as well? 

For reference, if you copy and paste these url's, you can see the JSONS and they all have a body of null as well:
```
 1: https://api.github.com/repos/sailuh/kaiaulu/pulls/347 2025-03-27T12:37:46Z
 2: https://api.github.com/repos/sailuh/kaiaulu/pulls/333 2024-12-09T00:01:19Z
 3: https://api.github.com/repos/sailuh/kaiaulu/pulls/332 2024-12-08T22:23:28Z
 4: https://api.github.com/repos/sailuh/kaiaulu/pulls/328 2024-11-12T22:17:31Z
 5: https://api.github.com/repos/sailuh/kaiaulu/pulls/297 2024-04-23T23:58:12Z
 6: https://api.github.com/repos/sailuh/kaiaulu/pulls/293 2024-04-06T00:29:51Z
 7: https://api.github.com/repos/sailuh/kaiaulu/pulls/205 2023-05-03T12:45:55Z
 8: https://api.github.com/repos/sailuh/kaiaulu/pulls/204 2023-05-03T12:27:44Z
 9: https://api.github.com/repos/sailuh/kaiaulu/pulls/167 2023-03-18T20:30:52Z
10: https://api.github.com/repos/sailuh/kaiaulu/pulls/161 2023-02-28T09:27:08Z
11: https://api.github.com/repos/sailuh/kaiaulu/pulls/160 2023-02-28T07:58:35Z
```
Edit 1: It is in fact the same issues that would come up when using the other function,github_parse_project_issue().

2025-11-11 04:37 UTC, carlosparadis commented
@geraldmjhuff 

One more thing. Since your initial motivation for this project was to gain more exposure, I would like you to try the following to tell the whole story of your investigation. You added the fix, but here's how you can add a unit test for data samples to this commit to pair with it. 

https://github.com/sailuh/kaiaulu/blob/9868c3d2d8e02b1be445c5a023d4f8e6530d8363/R/example.R#L402-L432

As you can see here, Kaiaulu has an API to fabricate synthetic data. We have one for JIRA as linked above, one for Git (we can create synthetic .git folder with commits), and Mail (synthetic e-mails). While the API of each one is within R/jira.R, R/git.R, etc, the examples that document edge cases in the data are all located in R/example.R. 

R/example.R purpose is to store these various synthetic examples as code. So if an example function is called, it will create the synthetic data on `/tmp` and subsequently delete it to cleanup. Who uses the example functions are the unit tests in Kaiaulu. 

So for the one above, you can use it being used on the following unit test: 

https://github.com/sailuh/kaiaulu/blob/9868c3d2d8e02b1be445c5a023d4f8e6530d8363/tests/testthat/test-jira.R#L8-L19

As you can see, we can test that if changes are done in the parse_jira function in the future, that edge case will always be accounted for. It also helps us ensure that if the JIRA API changes the data format in any way, the tests will fail before any analysis is done. 

So, this is the process for fixing edge cases: You conduct an investigation (as you just did), you pinpoint the exact example of data that causes the issue. You then add a unit test **before** you implement the fix to check the test fails (and indeed capture the issue). Then, you implement the fix, run the test again, and see that it works. 

In Kaiaulu, because we have a CI/CD pipeline implemented on GitHub, that means any future commit done to Kaiaulu will thereafter run that edge case example before I even have to look at the code. So to say, your investigation lives on in perpetuity, evaluating all the future contributors' code. Hence, for exposure to this, I would like you to contribute a unit test for your investigation. 

Because Kaiaulu does not have a fake data generator for GitHub, we will just do something simple that will have the same benefit. 

Simple add a new function to R/example.R and name it:

```r
example_github_issue_no_description(folder_path, folder_name)
```

Then, within it, all you have to do is manually craft the list itself (use the R function list). You can then save the list to tmp as a json, and compare the file you created synthetically indeed matches the raw data containing the null in all its fields. So to say, when you download the data from an issue, you want to get all the fields in it so it is a realistic replica. 

You can see an example here:

https://github.com/sailuh/kaiaulu/blob/9868c3d2d8e02b1be445c5a023d4f8e6530d8363/R/jira.R#L801-L827

You do not and should not spend time creating the sub-functions within the function above. Just hardcode the entire list() there. A future project can add the equivalent capability to GitHub.

Once you do that, go to R/tests/testthat/test-github.R ; the file does not exist so go ahead and create one. You can then replicate the way unit tests are created in test-jira.R as shown above. You can literally copy and paste and just replace the `example` function. 

Remember there is a fake data generator cheatsheet if it helps. 

If you find this comment confusing, I suggest you skip and proceed with the main pipeline. It is important we finish all the filters this week. 

Thanks!

2025-11-11 05:19 UTC, geraldmjhuff commented
@carlosparadis In my environment, this code in R/github.R in github_parse_project_issue():
```R
# For issues with "No description provided" in the top comment box; if body is NULL or empty, assign NA
parsed_response[["body"]] <- 
  if (length(api_response[["body"]]) == 0 || is.null(api_response[["body"]])) {
    NA_character_
  } else {
    api_response[["body"]]
  }

```
replaces `parsed_response[["body"]] <- api_response[["body"]]` and I was able to run the CLI using --issues successfully and got no errors. I've also tried this but didn't work:
```R
parsed_response[["body"]] <- 
  if (is.null(api_response[["body"]])) {
    NA_character_
  } else {
    api_response[["body"]]
  }
```
You can see this is the same code, but just without `length(api_response[["body"]]) == 0` if check inside of it. Should I commit the change of the first code block onto github_parse_project_issue()?

2025-11-11 07:27 UTC, carlosparadis commented
Why the == 0 || NULL and not one or the other?

2025-11-11 08:24 UTC, geraldmjhuff commented
@carlosparadis Hmm that is right, the code does just work with:
```R
# For issues with "No description provided" in the top comment box; if body is NULL or empty, assign NA
parsed_response[["body"]] <- 
  if (length(api_response[["body"]]) == 0) {
    NA_character_
  } else {
    api_response[["body"]]
  }
```
My mistake, I've autopiloted doing the `is.null(api_response[["body"]]` just because since the JSON has a null value, i'd just add the NA in place of it and think it would work, which is clearly not the case, as length(api_response[["body"]]) == 0 itself accommodates both null and zero-length vectors. Similar to how it is done in:
```R
parsed_response[["labels"]] <- api_response[["labels"]]
    if(length(parsed_response[["labels"]]) > 0){
      parsed_response[["labels"]] <- stringi::stri_c(sapply(parsed_response[["labels"]],"[[","name"),collapse = ",")
    }else{
      parsed_response[["labels"]] <- NA_character_
    }
```

2025-11-11 08:33 UTC, carlosparadis commented
One more clarification here: Are you saying that no description provided can either be null or empty? I would expect the GitHub API to be consistent in specifying either one or the other. Could you confirm? I'd rather have specific behavior, since I will implement the example json down the road on the unit test.

2025-11-11 08:35 UTC, carlosparadis commented
Also, I'd appreciate if you make the assignment explicit as done in the reference code:

```r
      parsed_response[["labels"]] <- NA_character_
``` 

as opposed to just 

```r
NA_character_
```

Go ahead and proceed with the > 0 as this is found elsewhere. But please let me know about the JSON. Also, I saw you pasted an example of null but could you attach the file here too? I think it will allow you to. 

Thank you for diagnosing this.

2025-11-11 09:30 UTC, geraldmjhuff commented
@carlosparadis The final version would look like:
```R
parsed_response[["body"]] <- api_response[["body"]]
if (length(parsed_response[["body"]]) > 0) {
  parsed_response[["body"]] <- parsed_response[["body"]]
} else {
  parsed_response[["body"]] <- NA_character_
}
```
which is similar in structure as :
```R
parsed_response[["labels"]] <- api_response[["labels"]]
    if(length(parsed_response[["labels"]]) > 0){
      parsed_response[["labels"]] <- stringi::stri_c(sapply(parsed_response[["labels"]],"[[","name"),collapse = ",")
    }else{
      parsed_response[["labels"]] <- NA_character_
    }
```
I will commit the top code into github_parse_project_issue() and github_parse_project_pull_request() (I am unsure if you read the comment but I will link it here https://github.com/sailuh/kaiaulu/pull/301#issuecomment-3514940461. It is an explanation why applying the same change will fix the same conflict to github_parse_project_pull_request() as well)

From what I can gather about what's happening, this works:
```R
parsed_response[["body"]] <- 
  if (length(api_response[["body"]]) == 0) {
    NA_character_
  } else {
    api_response[["body"]]
  }
```
but this doesent:

```R
parsed_response[["body"]] <- 
  if (is.null(api_response[["body"]]) {
    NA_character_
  } else {
    api_response[["body"]]
  }
```
`length(api_response[["body"]]) == 0` catches both NULL and empty vectors, while `api_response[["body"]]` only catches NULL. Because all relevant issues have a JSON containing "body":null, it should be the case that the if statement of `is.null(api_response[["body"]]` should be executed, but it doesn't. From this I can only deduce that "body": null is being parsed into a zero-length vector in R, which is why we can enter `length(api_response[["body"]]) == 0` but not `is.null(api_response[["body"]]`. If this is not the reason, im unsure of what it may be.

This is a JSON with "body":null
https://[api.github.com/repos/sailuh/kaiaulu/issues/204](https://api.github.com/repos/sailuh/kaiaulu/issues/204)

2025-11-11 09:36 UTC, carlosparadis commented
Please proceed with the commit so it is consistent with the rest of the codebase. Could you just check with a print() to check what the json library we use is parsing as? For future reference. 

Also, can you confirm if you are interested in trying the unit test? Otherwise I will make another issue and defer for the future. Either way is fine for me, just checking on your interests given your timeline to finish the filter and notebook.

As far as the merge is concerned, go ahead and do it, although I do think we will need to do one more once I get a chance to merge the PR for Pull Request API on main since the notebooks were refactored in name and slightly in content. We can worry about later on (or I will worry about it on the occasion).

Thanks for this!

2025-11-13 04:16 UTC, geraldmjhuff commented
@carlosparadis I have made a unit test with the specifications required mentioned in this [comment](https://github.com/sailuh/kaiaulu/pull/301#issuecomment-3514964448)
R/example.R:
```R
example_github_issue_no_description <- function(folder_path="/tmp", folder_name) {

  # Create folder
  folder_path <- io_make_folder(folder_path, folder_name)

  issue <- list(
    id = 1001,
    number = 42,
    html_url = "https://github.com/example/repo/issues/42",
    url = "https://api.github.com/repos/example/repo/issues/42",
    created_at = "2025-11-01T00:00:00Z",
    updated_at = "2025-11-02T00:00:00Z",
    state = "open",
    user = list(login = "test-user"),
    author_association = "random-name",
    title = "Issue #X",
    body = NULL,  
    labels = list(
      list(name = "bug"),
      list(name = "help wanted")
    )
  )

  jsonlite::write_json(list(issue),
                       file.path(folder_path, "ONE_ISSUE_NO_DESCRIPTION.json"))

  return(folder_path)
}
```
R/tests/testthat/test-github.R:
```R
test_that("fwrite fails if GitHub issue JSON has NULL body", {

  # Generate synthetic GitHub issue
  github_json_path <- example_github_issue_no_description("/tmp", "github_issue_no_desc")

  # Read JSON
  all_issue <- lapply(list.files(github_json_path, 
                                full.names = TRUE), jsonlite::read_json)

  # Bind as data.table 
  all_issue <- lapply(all_issue,
                        github_parse_project_issue)  

  all_issue <- rbindlist(all_issue,fill=TRUE)

  tmp_csv <- file.path(tempdir(), "test_null_body.csv")
  expect_silent(data.table::fwrite(all_issue, tmp_csv))
  
  if (dir.exists(file.path("/tmp", "github_issue_no_desc"))) {
    io_delete_folder("/tmp", "github_issue_no_desc")
  }
})
```
Given my procedure, please let me know if I finalized my unit test correctly:
1. Kept R/github.R `parsed_response[["body"]] <- api_response[["body"]]` (Before implementation fix)
2. While keeping 'example.R' and 'test-github.R' as is above, the test fails: 
```R
── Error (test-github.R:17:3): fwrite fails if GitHub issue JSON has NULL body ──
Error in `data.table::fwrite(all_issue, tmp_csv)`: Row 1 of list column is type 'NULL' - not yet implemented. fwrite() can write list columns containing items which are atomic vectors of type logical, integer, integer64, double, complex and character.
Backtrace:
    ▆
 1. ├─testthat::expect_silent(data.table::fwrite(all_issue, tmp_csv)) at test-github.R:17:3
 2. │ └─testthat:::quasi_capture(enquo(object), NULL, evaluate_promise)
 3. │   ├─testthat (local) .capture(...)
 4. │   │ ├─withr::with_output_sink(...)
 5. │   │ │ └─base::force(code)
 6. │   │ ├─base::withCallingHandlers(...)
 7. │   │ └─base::withVisible(code)
 8. │   └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
 9. └─data.table::fwrite(all_issue, tmp_csv)
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
> 
```
3. Now, we implement the fix to R/github.R: 
```R
parsed_response[["body"]] <- api_response[["body"]]
    if (length(parsed_response[["body"]]) > 0) {
      parsed_response[["body"]] <- parsed_response[["body"]]
    } else {
      parsed_response[["body"]] <- NA_character_
    }
```
4. Without changing R/example.R and test-github.R, the test passes:
```R
══ Testing test-github.R ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 1 ] Done!
```

Note:
1. I made test-github.R to have a similar code block as exec/github.R (Because this is how we first found out about the problem, and therefore we replicated it)
exec/github.R:
```R
save_path_issue <- get_github_issue_path(conf, project_key)

    all_issue <- lapply(list.files(save_path_issue,
                                   full.names = TRUE),read_json)
    all_issue <- lapply(all_issue,
                        github_parse_project_issue)
    all_issue <- rbindlist(all_issue,fill=TRUE)

    data.table::fwrite(all_issue, save_path)
    cli::cli_alert_success(paste0("Dependencies table was saved at: ", save_path))
```

2025-11-13 04:57 UTC, carlosparadis commented
Well done! Here are some minor adjustments:

# Test message

```r
> test_that("fwrite fails if GitHub issue JSON has NULL body", {
 ```

How about:

```r
> test_that("github issue without description can be parsed as NA", {
```

That way, when the test fail we know exactly the result of your investigation straight out of the test message.

# Test expectation

```
 expect_silent(data.table::fwrite(all_issue, tmp_csv))
```

Try a more specific test: The code is working as intended if a null body is assigned NA, so your expect should parse `all_issue` and then access its body column to `is.na()`. There is one expect that passes if the value is TRUE that I used in Kaiaulu but I don't remember from memory. Try using that instead.

Also, not sure what you are using `  tmp_csv <- file.path(tempdir(), "test_null_body.csv")` for. Once you create the json and parse it, you can expect the value from memory. Am I missing something here?

# Checking test fails and passes with your fix

Great! That's precisely how you want to go about every unit test. The prior to check you indeed capture the error, and the second that you indeed fixed it. 

What I recommend you do as a final exercise is this: Make a commit to GitHub with your unit test implemented, but without the solution. Have GitHub Actions fail, and check the "testing check" to see what you saw offline also occurs there. Then, add the fix and see if the GitHub Actions pass. Technically this is redundant, but it helps fixate the idea of how your unit test now will be applied to every commit instead of only when someone remembers to run tests offline.


I will take a closer look on all the other parts and variables once you push the code review, but I believe you understood it correctly! 

As a final note, I hope this serves as a learning exercise on how to test an API that relies on data. Other tools approach this differently: Some have an entire dataset versioned in their repo created on the fly, or version an actual project. Although you did not get the chance to test the fake data generator API, I think you can extrapolate from what you did to imagine there are sub-functions that parameterize the file format. 

NIce work 👍 

Edit: Somehow I managed to shortcut my keyboard to post the comment, post a new comment and close the PR (!!). Please disregard the crazy close and re-open!

2025-12-09 15:08 UTC, carlosparadis commented
@geraldmjhuff I almost forgot this. Is this ready for review? Anything you added on sentiment that should be here instead?

Edit: Also, did you apply the minor adjustments I asked above?

2025-12-10 06:00 UTC, geraldmjhuff commented
@carlosparadis 
Yes this PR should be ready for review, and I don't believe anything from sentiment should be here instead.

And yes I've also applied the minor adjustments above before making the commit.

2025-12-10 20:27 UTC, carlosparadis commented
@geraldmjhuff As you can see, I finally merged #323 to master. Could you do the git merge locally on your computer from master to see if your fixes conflict with what was pushed there? This would not only save me an immense amount of time, but it would also ensure your findings and fixes in this PR are not lost if I try to merge myself. 

Note vignettes/github_api_showcase.Rmd still exists, the file was just renamed to be download_events.Rmd. 

R/github.R and the associated parse_replies is likely where it affects you.

2025-12-12 08:43 UTC, geraldmjhuff commented
@carlosparadis 

I've made the merge from masters, exec/github.R and exec/ghevents.R works as intended, this PR should be ready for review.

2025-12-13 00:09 UTC, carlosparadis commented
Had entirely forgotten this PR had evolved to have the Process Mining exporter tied to sailuh/process_mining. Cleaned up some of the associated Notebook and edited the PR.

2025-12-13 01:40 UTC, carlosparadis approved these changes

2025-12-13 01:49 UTC, merged